### ISSUE TITLE
Install fails with stable PyTorch 1.12

### ISSUE THREAD

**Issue by biphasic** [synsense/sinabs-exodus#1]
Installing Exodus using `pip install .` when Pytorch 1.12 is installed results in
```
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/user/Development/sinabs-exodus/setup.py", line 10, in <module>
          if cpp_extension.check_compiler_abi_compatibility("g++"):
      AttributeError: module 'torch.utils.cpp_extension' has no attribute 'check_compiler_abi_compatibility'
      [end of output]
```

Weirdly enough they seemed to have simply dropped that function in the new version and replaced it with another one. Compare the two docs:

https://pytorch.org/docs/1.11/cpp_extension.html#torch.utils.cpp_extension.check_compiler_abi_compatibility

https://pytorch.org/docs/1.12/cpp_extension.html#torch.utils.cpp_extension.get_compiler_abi_compatibility_and_version

**Comment by biphasic** [comment]
fixed in 7ef050e7defb20568f770b53994cd7c02f80fd84
